name: SetupAzureTerraform
description: "Action used to setup and deploy to azure"
inputs:
  environment:
    description: "Environment (DEV or PROD)"
    required: true
  working-directory:
    description: "Dir where Azure code is present"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses:  actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      env:
        AZURE_CLIENT_ID: ${{ inputs.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}

      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Run Terraform Plan
      shell: bash
      working-directory: "${{ GITHUB.WORKSPACE }}/${{inputs.working-directory}}"
      run: |
        terraform init  # Initialize Terraform
        terraform plan  # Run Terraform plan
