name: Execute Azure Terraform Plan

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment (DEV or PROD)'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraformExecution:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Environment-Specific Azure Credentials
      run: |
        echo "AZURE_CLIENT_ID=${{ secrets[format('{0}_AZURE_CLIENT_ID', inputs.env)] }}" >> $GITHUB_ENV
        echo "AZURE_TENANT_ID=${{ secrets[format('{0}_AZURE_TENANT_ID', inputs.env)] }}" >> $GITHUB_ENV
        echo "AZURE_SUBSCRIPTION_ID=${{ secrets[format('{0}_AZURE_SUBSCRIPTION_ID', inputs.env)] }}" >> $GITHUB_ENV

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Run Terraform Plan
      working-directory: ./Azure  # Navigate to the Azure folder
      run: |
        terraform init  # Initialize Terraform
        terraform plan  # Run Terraform plan
