name: Azure Login with OIDC

on:
  push:
    branches:
      - feature/* 

permissions:
  id-token: write
  contents: read

jobs:
  AzureTerraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Run Terraform Plan
      working-directory: ./Azure  # Navigate to the Azure folder
      run: |
        terraform init  # Initialize Terraform
        terraform plan  # Run Terraform plan
        # terraform apply
        # sleep 100
        # terraform destroy
    
    
