name: Azure Terraform Workflow

on:
  issue_comment:
    types:
      - created  # Trigger only when a comment is created

permissions:
  id-token: write  # Required for Azure Login with OIDC
  contents: read

jobs:
  AzureTerraform:
    if: >
     github.event.issue.pull_request && (github.event.pull_request.merged == true || startsWith(github.event.comment.body,'terraform plan'))
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}  # Checkout the branch associated with the pull request

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Run Terraform Plan
      working-directory: ./Azure  # Navigate to the Azure folder
      id: terraform
      run: |
        terraform init  # Initialize Terraform
        terraform plan -out=tfplan  # Generate a Terraform plan
        tf_summary=$(terraform show -json tfplan )
        echo "TF_SUMMARY=$tf_summary" >> $GITHUB_ENV
  
    # - name: Comment on Pull Request
    #   uses: mshick/add-pr-comment@v2
    #   with:
    #     message: |
    #       ### Terraform Plan Summary
    #       ${{ env.TF_SUMMARY }}
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     repo-owner: ${{ github.repository_owner }}
    #     repo-name: ${{ github.event.repository.name }}
