name: Azure Login with OIDC

on:
  push:
    branches:
      - main  # Trigger only on push to main branch

permissions:
  id-token: write
  contents: read

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        federated-token: ${{ steps.github-token.outputs.token }}
    - name: Run Terraform Plan
      working-directory: ./Azure  # Navigate to the Azure folder
      run: |
        terraform init  # Initialize Terraform
        terraform plan  # Run Terraform plan
    
    
